gText_Olive_Welcome::
.string "Hello! Sorry to call unannounced\n"
.string "like this.\p"
.string "My name is OLIVE.\n"
.string "I knew you as a kid.\p"
.string "How are things back home on ILLOS?\p"
.string "$"

gText_Olive_Pokemon::
.string "This creature here… is called a\n"
.string "POKéMON.\p"
.string "$"
gText_Olive_MainSpeech::
.string "Back home in KYMA TOWN, you're used to\n"
.string "seeing them hard at work- pulling plows,\l"
.string "hauling cargo, keeping the island\l"
.string "running, etcetera.\p"
.string "For generations, ILLIANS have thought\n"
.string "of them primarily as working animals.\p"
.string "But during my travels to other regions,\n"
.string "I began to see POKéMON in a new way.\p"
.string "I met trainers who worked alongside\n"
.string "their POKéMON and cared for them.\p"
.string "I met professors who studied POKéMON\n"
.string "not as tools, but as living creatures\l"
.string "with minds, feelings, and lives of their\l"
.string "own.\p"
.string "And, little by little, I began to wonder…\n"
.string "what if I'd been looking at POKéMON all\l"
.string "wrong?\p"
.string "Since then, I've wanted to understand\n"
.string "them better- and help others do the\l"
.string "same.\l"
.string "That's why I haven't been home in years.\p"
.string "$"

gText_Olive_AndYouAre::
.string "Ah, but enough about me.\p"
.string "Forgive me, but it's been 15 years\n"
.string "since I last saw you.\p"
.string "I… uhm… forgot your face…\p"
.string "$"

gText_NewGame_ChooseTones::
.string "What do you look like, again?"
.string "$"

gText_Olive_WhatsYourName::
.string "Right then.\n"
.string "And… uhm…\p"
.string "… … … … … … … …\n"
.string "… … … … … … … …\p"
.string "what is your name?$"

gText_Olive_SoItsPlayer::
.string "So you're {PLAYER}{KUN}?$"

gText_Olive_YourePlayer::
.string "Ah, of course!\p"
.string "{PLAYER}{KUN}!\n"
.string "How could I forget?\p"
.string "It'll be great to see you again.\p"
.string "$"

gText_Olive_AreYouReady::
.string "Now then… are you ready?\p"
.string "You've spent your life in KYMA TOWN, but\n"
.string "a vast world lies out there for you.\p"
.string "Step out there, explore, and discover\n"
.string "what these creatures are truly\l"
.string "capable of.\p"
.string "My ship will be arriving in town later.\n"
.string "Come see me if you get the chance.\p"
.string "OH, RIGHT- Happy 16th birthday! Tell your\n"
.string "twin I said happy birthday to him, too.\l"
.string "Ta léme!\p"
.string "$"
