gText_Olive_Welcome::
.string "Ah, welcome! Sorry to keep you waiting.\p"
.string "How are things back home on ILLOS?\p"
.string "My name is OLIVE.\p"
.string "$"

gText_Olive_Pokemon::
.string "This creature here… is called a\n"
.string "POKéMON.\p"
.string "$"
gText_Olive_MainSpeech::
.string "Back home in KYMA TOWN, you're used to\n"
.string "seeing them hard at work- pulling plows,\l"
.string "hauling cargo, keeping the island\l"
.string "running, etcetera.\p"
.string "For generations, ILLIANS have thought\n"
.string "of them primarily as working animals.\p"
.string "But during my travels to other regions,\n"
.string "I began to see POKéMON in a new way.\p"
.string "I met trainers who worked alongside\n"
.string "their POKéMON and cared for them, and,\l"
.string "OH!\l"
.string "There was this ADORABLE little salon\l"
.string "in KALOS, and in GALAR they could grow\l"
.string "MASSIVE, and-\p"
.string "Sorry, ranting, uhm…\n"
.string "they trusted and loved each other.\p"
.string "I met professors who studied POKéMON\n"
.string "not as tools, but as living creatures\l"
.string "with minds, feelings, and lives of their\l"
.string "own.\p"
.string "And, little by little, I began to wonder…\n"
.string "what if we'd been looking at POKéMON all\l"
.string "wrong?\p"
.string "Since then, I've wanted to understand\n"
.string "them better- and help others do the\l"
.string "same.\l"
.string "That's why I haven't been home in years.\p"
.string "$"

gText_Olive_AndYouAre::
.string "Ah, but enough about me.\p"
.string "Forgive me, but it's been so long\n"
.string "since I last saw you.\p"
.string "I… uhm… forgot your face…\p"
.string "$"

gText_NewGame_ChooseTones::
.string "What do you look like, again?"
.string "$"

gText_Olive_WhatsYourName::
.string "Right then.\n"
.string "And… uhm…\l"
.string "… … … … … … … …\l"
.string "… … … … … … … …\l"
.string "what is your name?\l"
.string "(please don't hate me…)$"

gText_Olive_SoItsPlayer::
.string "So you're {PLAYER}{KUN}?$"

gText_Olive_YourePlayer::
.string "Ah, of course!\p"
.string "{PLAYER}{KUN}!\n"
.string "How could I forget?\p"
.string "It'll be great to see you again.\p"
.string "$"

gText_Olive_AreYouReady::
.string "Now then… are you ready?\p"
.string "You've spent your life in KYMA TOWN, but\n"
.string "a vast world lies out there for you.\p"
.string "Step out there, explore, and discover\n"
.string "what these creatures are truly\l"
.string "capable of.\p"
.string "My ship will be arriving in town later.\n"
.string "Come see me if you get the chance.\l"
.string "Ta léme!\p"
.string "$"
