DadsFarm_House_1F_MapScripts::
	.byte 0

DadsFarm_House_1F_EventScript_Fridge::
	msgbox DadsFarm_House_1F_Text_Fridge, MSGBOX_SIGN
	end

DadsFarm_House_1F_EventScript_Sink::
	msgbox DadsFarm_House_1F_Text_Sink, MSGBOX_SIGN
	end

DadsFarm_House_1F_EventScript_Window::
	msgbox DadsFarm_House_1F_Text_Window, MSGBOX_SIGN
	end

DadsFarm_House_1F_EventScript_DryingMeats::
	msgbox DadsFarm_House_1F_Text_DryingMeats, MSGBOX_SIGN
	end

DadsFarm_House_1F_EventScript_Pantry::
	msgbox DadsFarm_House_1F_Text_Pantry, MSGBOX_SIGN
	end

DadsFarm_House_1F_Text_Fridge:
	.string "An old-fashioned ice chest.\n"
	.string "It keeps the goat milk fresh and cool.$"

DadsFarm_House_1F_Text_Sink:
	.string "A stone sinkbasin filled with water\n"
	.string "drawn fresh from the well.\l"
  .string "We just had the plumbing installed!$"

DadsFarm_House_1F_Text_Window:
	.string "The view looks out over the olive\n"
	.string "groves. The sun is warm.$"

DadsFarm_House_1F_Text_DryingMeats:
	.string "Racks of cured meats and wild herbs\n"
	.string "hang here to dry. It smells savory.$"

DadsFarm_House_1F_Text_Pantry:
	.string "Large storage boxes line the wall.\n"
	.string "They're packed with feta and olives!$"
